### ISSUE TITLE
ask for some help

### ISSUE THREAD

**Issue by yyyloo** [shuchaoduan/QAFE-Net#2]
Hello, dear shuchaoduan, my research direction is pain recognition, but there are few processing methods related to the UNBC database. I am a novice. I saw that you have used the UNBC database in your paper. I would like to know if you can provide me with detailed processing code for it. I would be very grateful for your help

**Comment by shuchaoduan** [comment]
> Hello, dear shuchaoduan, my research direction is pain recognition, but there are few processing methods related to the UNBC database. I am a novice. I saw that you have used the UNBC database in your paper. I would like to know if you can provide me with detailed processing code for it. I would be very grateful for your help

Hi there, Thanks for your interest. I’ve made some additional updates to the preprocessing code in this repo. I hope it can help you.
